# Generated by Django 5.0.1 on 2024-07-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
