# Generated by Django 5.0.1 on 2024-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('tagline', models.TextField()),
                ('primary_colour', models.CharField(default='#FFFFFF', max_length=7)),
                ('secondary_colour', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
