# Generated by Django 5.0.1 on 2024-06-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdetails',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='display_club_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='display_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='postcode',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='primary_text_colour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='secondary_text_colour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
