# Generated by Django 5.0.1 on 2024-06-30 08:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clubdetails_address_line1_clubdetails_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
