# Generated by Django 5.0.1 on 2024-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clubdetails_footer_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetails',
            name='footer_colour',
            field=models.CharField(default='#0e0e14', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='footer_text_colour',
            field=models.CharField(default='#ddd7d4', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='header_colour',
            field=models.CharField(default='#0e0e14', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='header_text_colour',
            field=models.CharField(default='#ddd7d4', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='primary_colour',
            field=models.CharField(default='#ddd7d4', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='primary_text_colour',
            field=models.CharField(default='#0e0e14', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='secondary_colour',
            field=models.CharField(default='#df0020', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='secondary_text_colour',
            field=models.CharField(default='#ddd7d4', max_length=7),
        ),
    ]
