# Generated by Django 5.0.1 on 2024-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
