# Generated by Django 5.0.1 on 2024-07-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='club',
        ),
    ]
